### ISSUE TITLE
Add icon to external links

### ISSUE THREAD

**Issue by timvink** [JakubAndrysek/mkdocs-open-in-new-tab#4]
It would be cool if you could add an option to enable adding an icon behind links to show that links open in a new tab.

Something like this:

```yaml
# mkdocs.yaml
plugins:
  - search
  - open-in-new-tab:
      add_icon: true
``` 

Then it could look like this:

<img width="348" alt="image" src="https://github.com/JakubAndrysek/mkdocs-open-in-new-tab/assets/5570380/4daf03fb-2c6a-400c-b68a-23ba574d1848">

Mkdocs-material already has a nice set of icons you can choose from

<img width="546" alt="image" src="https://github.com/JakubAndrysek/mkdocs-open-in-new-tab/assets/5570380/c2e97f55-d805-435a-8cc4-e441918823a2">

Technically, you would have to add an extra event event that processes and updates either the markdown or the HTML. An example of a plugin that does this is [table-reader](https://github.com/timvink/mkdocs-table-reader-plugin/blob/master/mkdocs_table_reader_plugin/plugin.py)

**Comment by JakubAndrysek** [comment]
I have tested adding icons using JS, but it will also add icons next to the images and to the top Github link.
So I will have to modify the generated HTML as you wrote in the previous comment.

![image](https://github.com/JakubAndrysek/mkdocs-open-in-new-tab/assets/33494544/b68e3b3c-b474-4443-927c-21c6c0c5dd6a)

**Comment by timvink** [comment]
Looks great though

**Comment by ebouchut** [comment]
@timvink @JakubAndrysek 
There is another way to insert the up-arrow image beside each link.
Instead of JS, you could **use** a **CSS** rule, like this:

```css
/*
 * Materialize links that open in a new window with a right-up arrow icon
 */
a[target="_blank"]::after {
  content: "↗";
  display: inline-block;
  margin-left: 0.2em;
  width: 1em;
  height: 1em;
}
```

**Comment by JakubAndrysek** [comment]
Thank you very much. I have implemented your CSS helper to the code

**Comment by ebouchut** [comment]
I need to figure out how to exclude the footer and the header in the CSS selector.

**Comment by ebouchut** [comment]
This rule would help even if it may also remove text that _Mkdocs_ adds after the links.

```css
/*
 * Does not add text (up-right arrow) after the links in the header and footer
 */
.md-header a[target="_blank"]::after,
.md-footer a[target="_blank"]::after {
  content: none;
}
```
